name: Test
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Get Spack
      working-directory: ${{ github.workspace }}
      run: |
        git clone https://github.com/spack/spack
        pwd
        ls -la
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        export SPACK_ROOT=/home/runner/work/pySpack/pySpack/spack
        cd src && python -m unittest discover pySpack
    - name: Build a wheel package
      run: |
        cd src && pip install setuptools wheel twine && python setup.py sdist bdist_wheel